modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]] #mandatory
modId = "create_creative_tweaks"
version = "${file.jarVersion}"
displayName = "Create: Creative Tweaks"
authors = "Katie"
displayTest = "IGNORE_ALL_VERSION" # Doesn't matter if it's only on the client or server - QOL
description = '''
Various client-sided and creative-only utility tweaks for Create and addons.
'''

[[dependencies."create_creative_tweaks"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."create_creative_tweaks"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."create_creative_tweaks"]]
modId = "create"
mandatory = true
versionRange = "[0.5.1f,)"
ordering = "NONE"
side = "BOTH"